//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarhammerClient.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarhammerClient.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action summary.
        /// </summary>
        internal static string ActionSummary {
            get {
                return ResourceManager.GetString("ActionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string ActualXP {
            get {
                return ResourceManager.GetString("ActualXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        internal static string Advance {
            get {
                return ResourceManager.GetString("Advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced armour.
        /// </summary>
        internal static string AdvancedArmour {
            get {
                return ResourceManager.GetString("AdvancedArmour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        internal static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aim.
        /// </summary>
        internal static string Aim {
            get {
                return ResourceManager.GetString("Aim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP.
        /// </summary>
        internal static string AP {
            get {
                return ResourceManager.GetString("AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour.
        /// </summary>
        internal static string Armour {
            get {
                return ResourceManager.GetString("Armour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour points.
        /// </summary>
        internal static string ArmourPoints {
            get {
                return ResourceManager.GetString("ArmourPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour type.
        /// </summary>
        internal static string ArmourType {
            get {
                return ResourceManager.GetString("ArmourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic action.
        /// </summary>
        internal static string BasicAction {
            get {
                return ResourceManager.GetString("BasicAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic armour.
        /// </summary>
        internal static string BasicArmour {
            get {
                return ResourceManager.GetString("BasicArmour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth place.
        /// </summary>
        internal static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book of rules.
        /// </summary>
        internal static string BookOfRules {
            get {
                return ResourceManager.GetString("BookOfRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS.
        /// </summary>
        internal static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        internal static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign name.
        /// </summary>
        internal static string CampaignName {
            get {
                return ResourceManager.GetString("CampaignName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign year.
        /// </summary>
        internal static string CampaignYear {
            get {
                return ResourceManager.GetString("CampaignYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        internal static string Cast {
            get {
                return ResourceManager.GetString("Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character profile.
        /// </summary>
        internal static string CharacterProfile {
            get {
                return ResourceManager.GetString("CharacterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character name.
        /// </summary>
        internal static string CharactersName {
            get {
                return ResourceManager.GetString("CharactersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character race.
        /// </summary>
        internal static string CharactersRace {
            get {
                return ResourceManager.GetString("CharactersRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge attack.
        /// </summary>
        internal static string ChargeAttack {
            get {
                return ResourceManager.GetString("ChargeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combta movement.
        /// </summary>
        internal static string CombatMovement {
            get {
                return ResourceManager.GetString("CombatMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create character.
        /// </summary>
        internal static string CreateCharacter {
            get {
                return ResourceManager.GetString("CreateCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new character.
        /// </summary>
        internal static string CreatingNewCharacter {
            get {
                return ResourceManager.GetString("CreatingNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current career.
        /// </summary>
        internal static string CurrentCareer {
            get {
                return ResourceManager.GetString("CurrentCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defensive stance.
        /// </summary>
        internal static string DefensiveStance {
            get {
                return ResourceManager.GetString("DefensiveStance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete character.
        /// </summary>
        internal static string DeleteCharacter {
            get {
                return ResourceManager.GetString("DeleteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfy są rasą smukłych, pełnych gracji istot, z łatwością rozpoznawalnych dzięki ostrym rysom twarzy i spiczasto zakończonym uszom. Znane są z talentu do łucznictwa, zamiłowania do wiedzy i zdolności magicznych. To istoty blisko związane z naturą. Instynktownie wyczuwają wszelkie zmiany w przyrodzie, szczególnie w ostępach leśnych, ale także na morzu. Nienawidzą wszystkich, którzy zakłócają harmonię natury, niezależnie od rasy. Z równą gwałtownością przeciwstawiają się działaniom złych ludzi i chciwych krasn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionRaceElf {
            get {
                return ResourceManager.GetString("DescriptionRaceElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ludzie są najliczniejsza rasa w Starym  Świecie i założycielami największego państwa, czyli Imperium. Chociaż nie są tak mądrzy jak elfy, ani równie wytrzymali jak krasnoludy, ludzie to rasa, która swoja ambicja i determinacja przewyższa wszystkie pozostałe. Są wyjątkowo elastyczni, co jest zarówna ich wielką zaletą jak i poważna słabością.  Mimo iż wielu ludzi wsławiło się heroicznymi czynami w walce z silami ciemności, to jednak smutna prawda pozostaje fakt, że ludzie najłatwiej ze wszystkich ras poddaj s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionRaceHuman {
            get {
                return ResourceManager.GetString("DescriptionRaceHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedstawiciela jakiej rasy chciałbyś odgrywać ? W świecie Warhammera możesz wybierać spośród czterech głównych ras: elfów, krasnoludów, ludzi i niziołków. Każda z nich ma swoje dobre i złe strony. Po przeczytaniu zamieszczonych poniżej opisów czterech ras, powinieneś wybrać tę, która najbardziej Ci odpowiada..
        /// </summary>
        internal static string DescriptionRaceSelection {
            get {
                return ResourceManager.GetString("DescriptionRaceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice.
        /// </summary>
        internal static string Dice {
            get {
                return ResourceManager.GetString("Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disengage.
        /// </summary>
        internal static string Disengage {
            get {
                return ResourceManager.GetString("Disengage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguishing marks.
        /// </summary>
        internal static string DistinguishingMarks {
            get {
                return ResourceManager.GetString("DistinguishingMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        internal static string Dwarf {
            get {
                return ResourceManager.GetString("Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        internal static string Elf {
            get {
                return ResourceManager.GetString("Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enc.
        /// </summary>
        internal static string Enc {
            get {
                return ResourceManager.GetString("Enc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience points.
        /// </summary>
        internal static string ExperiencePoints {
            get {
                return ResourceManager.GetString("ExperiencePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye color.
        /// </summary>
        internal static string EyeColor {
            get {
                return ResourceManager.GetString("EyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL.
        /// </summary>
        internal static string FEL {
            get {
                return ResourceManager.GetString("FEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP.
        /// </summary>
        internal static string FP {
            get {
                return ResourceManager.GetString("FP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Master.
        /// </summary>
        internal static string GameMaster {
            get {
                return ResourceManager.GetString("GameMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of GameMaster.
        /// </summary>
        internal static string GameMastersName {
            get {
                return ResourceManager.GetString("GameMastersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarhammerRPG 2.0 by Linaq.
        /// </summary>
        internal static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game rules.
        /// </summary>
        internal static string GameRules {
            get {
                return ResourceManager.GetString("GameRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarded attack.
        /// </summary>
        internal static string GuardedAttack {
            get {
                return ResourceManager.GetString("GuardedAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair color.
        /// </summary>
        internal static string HairColor {
            get {
                return ResourceManager.GetString("HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfling.
        /// </summary>
        internal static string Halfling {
            get {
                return ResourceManager.GetString("Halfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia elfów jest jednocześnie chwalebna i tragiczna. Pod koniec wojny z krasnoludami, zwanej przez elfy Wojną o Brodę, Wysokie Elfy odpłynęły do Ulthuanu, ich zamorskiej ojczyzny, by tam walczyć z najazdem Mrocznych Elfów. Byli jednak wśród nich tacy, którzy postanowili pozostać w Starym Świecie. Niektórzy wymówili posłuszeństwo Królowi Feniksowi i zajęli się budowaniem własnej przyszłości w leśnych królestwach. Inni, jak dawniej, podróżowali po morzach, nawiązując handel z powoli rodzącymi się królestwa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HisotryElf {
            get {
                return ResourceManager.GetString("HisotryElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W porównaniu do elfów i krasnoludów ludzie są rasą dość młodą, jednakże bardzo płodną. Szybko rozprzestrzenili się po całym świecie, korzystając z powolnego wymierania starszych ras. Kilka tysięcy lat temu do Starego Świata przybyła z południa grupa ludzkich plemion, które stały się założycielami Imperium, a także pozostałych krain; Bretonii, Estalii, Kisleva i Tilei. Inne plemiona podążyły na północ, aż do mroźnej Norski lub nawet jeszcze dalej. 
        ///Obywatele Imperium są dumni ze swoich osiągnieć. Ich główny [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HistoryHuman {
            get {
                return ResourceManager.GetString("HistoryHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string Human {
            get {
                return ResourceManager.GetString("Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT.
        /// </summary>
        internal static string INT {
            get {
                return ResourceManager.GetString("INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        internal static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump leap.
        /// </summary>
        internal static string JumpLeap {
            get {
                return ResourceManager.GetString("JumpLeap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageT {
            get {
                return ResourceManager.GetString("LanguageT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left arm.
        /// </summary>
        internal static string LeftArm {
            get {
                return ResourceManager.GetString("LeftArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left leg.
        /// </summary>
        internal static string LeftLeg {
            get {
                return ResourceManager.GetString("LeftLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations covered.
        /// </summary>
        internal static string LocationsCovered {
            get {
                return ResourceManager.GetString("LocationsCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAG.
        /// </summary>
        internal static string MAG {
            get {
                return ResourceManager.GetString("MAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main attributes.
        /// </summary>
        internal static string MainAttributes {
            get {
                return ResourceManager.GetString("MainAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MainCharacterProfile {
            get {
                return ResourceManager.GetString("MainCharacterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move/Disengage.
        /// </summary>
        internal static string MoveDisengage {
            get {
                return ResourceManager.GetString("MoveDisengage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My character.
        /// </summary>
        internal static string MyCharacter {
            get {
                return ResourceManager.GetString("MyCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name_Nazwa {
            get {
                return ResourceManager.GetString("name_Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of siblings.
        /// </summary>
        internal static string NumberOfSiblings {
            get {
                return ResourceManager.GetString("NumberOfSiblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parrying stance.
        /// </summary>
        internal static string ParryingStance {
            get {
                return ResourceManager.GetString("ParryingStance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal details.
        /// </summary>
        internal static string PersonalDetails {
            get {
                return ResourceManager.GetString("PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name.
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous careers.
        /// </summary>
        internal static string PreviousCareers {
            get {
                return ResourceManager.GetString("PreviousCareers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualities.
        /// </summary>
        internal static string Qualities {
            get {
                return ResourceManager.GetString("Qualities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right arm.
        /// </summary>
        internal static string RightArm {
            get {
                return ResourceManager.GetString("RightArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right leg.
        /// </summary>
        internal static string RightLeg {
            get {
                return ResourceManager.GetString("RightLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string sas {
            get {
                return ResourceManager.GetString("sas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; close.
        /// </summary>
        internal static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SB.
        /// </summary>
        internal static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string SecondaryCharacterProfile {
            get {
                return ResourceManager.GetString("SecondaryCharacterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Race.
        /// </summary>
        internal static string SelectRace {
            get {
                return ResourceManager.GetString("SelectRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills / Talents.
        /// </summary>
        internal static string SkillsTalents {
            get {
                return ResourceManager.GetString("SkillsTalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Grimoire.
        /// </summary>
        internal static string SpellGrimoire {
            get {
                return ResourceManager.GetString("SpellGrimoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard attack.
        /// </summary>
        internal static string StandardAttack {
            get {
                return ResourceManager.GetString("StandardAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand/Mount.
        /// </summary>
        internal static string StandMount {
            get {
                return ResourceManager.GetString("StandMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star sign.
        /// </summary>
        internal static string StarSign {
            get {
                return ResourceManager.GetString("StarSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent.
        /// </summary>
        internal static string Talent {
            get {
                return ResourceManager.GetString("Talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talents.
        /// </summary>
        internal static string Talents {
            get {
                return ResourceManager.GetString("Talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string TB {
            get {
                return ResourceManager.GetString("TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalXP {
            get {
                return ResourceManager.GetString("TotalXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a skill.
        /// </summary>
        internal static string UseASkill {
            get {
                return ResourceManager.GetString("UseASkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP.
        /// </summary>
        internal static string WP {
            get {
                return ResourceManager.GetString("WP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS.
        /// </summary>
        internal static string WS {
            get {
                return ResourceManager.GetString("WS", resourceCulture);
            }
        }
    }
}
